import { IPost } from "./../interfaces/index";
export const mockPosts: IPost[] = [
  {
    author: "Lainey Ritter",
    authorId: 1,
    id: 76,
    likes: 122,
    popularity: 0.01,
    reads: 75771,
    tags: ["tech", "health", "politics"],
  },
  {
    author: "Jaden Bryant",
    authorId: 3,
    id: 51,
    likes: 487,
    popularity: 0.01,
    reads: 98798,
    tags: ["design", "startups", "tech"],
  },
  {
    author: "Jon Abbott",
    authorId: 4,
    id: 43,
    likes: 149,
    popularity: 0.07,
    reads: 77776,
    tags: ["science", "tech"],
  },
  {
    author: "Lainey Ritter",
    authorId: 1,
    id: 82,
    likes: 140,
    popularity: 0.09,
    reads: 3201,
    tags: ["tech"],
  },
  {
    author: "Jaden Bryant",
    authorId: 3,
    id: 18,
    likes: 983,
    popularity: 0.09,
    reads: 33952,
    tags: ["tech", "history"],
  },
  {
    author: "Trevon Rodriguez",
    authorId: 5,
    id: 58,
    likes: 466,
    popularity: 0.1,
    reads: 17389,
    tags: ["science", "tech"],
  },
  {
    author: "Elisha Friedman",
    authorId: 8,
    id: 25,
    likes: 365,
    popularity: 0.12,
    reads: 32949,
    tags: ["politics", "tech"],
  },
];
